Niraj s sharma 4 ni19 is056
devdinstructor/dev-ops pull request #90
Opened 2022-12-08 17:35 UTC by Niraj-S-Sharma-056

Assignment 1

2022-12-08 17:36 UTC, JAGANNATH-R-KULAKARNI approved these changes
I approve

2022-12-08 17:55 UTC, JAGANNATH-R-KULAKARNI requested changes
Correct it

2022-12-08 17:56 UTC, JAGANNATH-R-KULAKARNI approved these changes

2022-12-25 04:35 UTC, devdinstructor requested changes
Submit actual assignments.

2023-01-01 18:38 UTC, closed without merging